// Constants for the game
export const BULLET_SIZE = 20;
export const CURSOR_SIZE = 80;
export const TARGET_WIDTH = 100;
export const BULLET_DURATION = 2000;
export const BULLET_HOLE_SIZE = 20;
export const MAX_TARGETS = 5;
export const TOT_SHOTS = 6;
export const FONT_SIZE = 25;
